FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY src ./src

FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app .

USER node

EXPOSE 3000

CMD ["npm", "start"]
