replicaCount: 1

image:
  repository: backend
  tag: v1
  pullPolicy: Never

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 300m
    memory: 256Mi
