replicaCount: 1

image:
  repository: ghcr.io/ravindranathsingh/backend
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 300m
    memory: 256Mi
